version: '3.8'
services:
  exercise:
    image: exercise
    environment:
      - JWT_SECRET
      - JWT_EXPIRATION_TIME
      - NODE_ENV
    ports:
      - '3334:3334'
    depends_on:
      - user
  user:
    image: user
    environment:
      - JWT_SECRET
      - JWT_EXPIRATION_TIME
      - NODE_ENV
    ports:
      - '3333:3333'
    depends_on:
      - sqlite3

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - "./local-db:/go/src/beginnerapp/local-db"
